# Generated by Django 4.1.3 on 2022-12-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_asha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=10)),
                ('id_proof', models.FileField(upload_to='media/patient/documents')),
                ('patient_pic', models.ImageField(upload_to='media/patient/pictures')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.asha')),
            ],
        ),
    ]
